admin_logout:
    pattern: /logout

admin_index:
    pattern: /
    defaults: { _controller: BackendBundle:Backend:index }

admin_categories:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix: /category/

admin_subcategories:
    resource: "@BackendBundle/Resources/config/routing/subcategory.yml"
    prefix: /subcategory/

admin_users:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix: /user/

admin_items:
    resource: "@BackendBundle/Resources/config/routing/item.yml"
    prefix: /product/

admin_orders:
    resource: "@BackendBundle/Resources/config/routing/order.yml"
    prefix: /order/

admin_manufacturers:
    resource: "@BackendBundle/Resources/config/routing/manufacturer.yml"
    prefix: /manufacturer/

admin_recent_orders:
    pattern: /recent-orders
    defaults: { _controller: BackendBundle:Backend:getRecentOrders }