imports:
    - { resource: "../../../../../app/config/parameters.yml" }

parameters:
    category.categoryformhandler.class: Ecommerce\BackendBundle\Form\Handler\CategoryFormHandler

services:
    category.category_form_handler:
            class: %category.categoryformhandler.class%
            arguments: [@doctrine.orm.entity_manager]
