cart:
    resource: "@CartBundle/Resources/config/routing.yml"
    prefix:   /

pay_pal:
    resource: "@PayPalBundle/Resources/config/routing.yml"
    prefix:   /

location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /bo

order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /

item:
    resource: "@ItemBundle/Resources/config/routing.yml"
    prefix:   /

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /u

login:
    pattern: /login
    defaults: { _controller: UserBundle:Access:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout