frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /bo

order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /

item:
    resource: "@ItemBundle/Resources/config/routing.yml"
    prefix:   /

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

