security:
    encoders:
        Ecommerce\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user:
            entity: { class: Ecommerce\UserBundle\Entity\User, property: email }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        user:
            pattern: ^/
            provider: user
            anonymous: ~
            form_login:
               login_path: login
               check_path: login_check
               success_handler: security.authentication.success_handler
               default_target_path: /u/mi-cuenta
            logout:
               path: logout
            remember_me:
               key: %secret%
               lifetime: 5184000

    access_control:
        - { path: ^/u/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/email-disponible, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/recuperar-contrasena, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/*, roles: ROLE_USER }
