parameters:
    order.order_event_listener.class: Ecommerce\OrderBundle\EventListener\OrderEventListener

services:
    order.order_event_listener:
        class: %order.order_event_listener.class%
        arguments: [@mailer, @templating, @router, %noreply_email%]
        tags:
            - { name: kernel.event_subscriber }