admin_delivery_index:
    pattern: /
    defaults: { _controller: BackendBundle:Delivery:list }

admin_delivery_edit:
    pattern: /edit/{id}
    defaults: { _controller: BackendBundle:Delivery:edit }

admin_delivery_delete:
    pattern: /delete/{id}
    defaults: { _controller: BackendBundle:Delivery:delete }

admin_delivery_create:
    pattern: /create
    defaults: { _controller: BackendBundle:Delivery:create }