admin_item_index:
    pattern: /
    defaults: { _controller: BackendBundle:Item:list }

admin_item_view:
    pattern: /view/{slug}
    defaults: { _controller: BackendBundle:Item:view }

admin_item_edit:
    pattern: /edit/{slug}
    defaults: { _controller: BackendBundle:Item:edit }

admin_item_delete:
    pattern: /delete/{slug}
    defaults: { _controller: BackendBundle:Item:delete }

admin_item_create:
    pattern: /create
    defaults: { _controller: BackendBundle:Item:create }

admin_item_upload_images:
    pattern: /upload-images/{id}
    defaults: { _controller: BackendBundle:Item:uploadImages }