admin_item_index:
    pattern: /
    defaults: { _controller: BackendBundle:Item:list }

admin_item_view:
    pattern: /view/{slug}
    defaults: { _controller: BackendBundle:Item:view }

admin_item_edit:
    pattern: /edit/{slug}
    defaults: { _controller: BackendBundle:Item:edit }

admin_item_delete:
    pattern: /delete/{slug}
    defaults: { _controller: BackendBundle:Item:delete }

admin_item_create:
    pattern: /create
    defaults: { _controller: BackendBundle:Item:create }

admin_item_upload_images:
    pattern: /upload-images/{id}
    defaults: { _controller: BackendBundle:Item:uploadImages }

admin_item_package_index:
    pattern: /packages
    defaults: { _controller: BackendBundle:ItemPackage:list }

admin_item_package_edit:
    pattern: /packages/edit/{slug}
    defaults: { _controller: BackendBundle:ItemPackage:edit }

admin_item_package_delete:
    pattern: /packages/delete/{slug}
    defaults: { _controller: BackendBundle:ItemPackage:delete }

admin_item_package_create:
    pattern: /packages/create
    defaults: { _controller: BackendBundle:ItemPackage:create }