admin_manufacturer_index:
    pattern: /
    defaults: { _controller: BackendBundle:Manufacturer:list }

admin_manufacturer_edit:
    pattern: /edit/{slug}
    defaults: { _controller: BackendBundle:Manufacturer:edit }

admin_manufacturer_delete:
    pattern: /delete/{slug}
    defaults: { _controller: BackendBundle:Manufacturer:delete }

admin_manufacturer_create:
    pattern: /create
    defaults: { _controller: BackendBundle:Manufacturer:create }