admin_order_index:
    pattern: /
    defaults: { _controller: BackendBundle:Order:list }

admin_order_view:
    pattern: /{id}
    defaults: { _controller: BackendBundle:Order:view }

admin_order_delete_item:
    pattern: /delete-item/{itemId}/{orderId}
    defaults: { _controller: BackendBundle:Order:deleteItem }

admin_order_send:
    pattern: /send-item/{id}
    defaults: { _controller: BackendBundle:Order:markAsSent }

admin_order_ready_to_take:
    pattern: /ready-to-take/{id}
    defaults: { _controller: BackendBundle:Order:markAsReadyToTake }

admin_order_out_of_stock:
    pattern: /out-of-stock/{id}
    defaults: { _controller: BackendBundle:Order:markAsOutOfStock }