admin_user_index:
    pattern: /
    defaults: { _controller: BackendBundle:User:list }

admin_user_view:
    pattern: /{id}
    defaults: { _controller: BackendBundle:User:view }

admin_user_edit:
    pattern: /edit/{id}
    defaults: { _controller: BackendBundle:User:edit }

admin_user_delete:
    pattern: /delete/{id}
    defaults: { _controller: BackendBundle:User:delete }

admin_user_validate:
    pattern: /validate/{id}
    defaults: { _controller: BackendBundle:User:validate }

admin_user_reactivate:
    pattern: /reactivate/{id}
    defaults: { _controller: BackendBundle:User:reactivate }