parameters:
    image.image_manager.class: Ecommerce\ImageBundle\Form\Handler\ImageManager
    image.create_image_form.class: Ecommerce\ImageBundle\Form\Handler\CreateImageFormHandler

services:
    image.manager:
        class: %image.image_manager.class%
        arguments: [@doctrine.orm.entity_manager]
    image.form_handler:
        class: %image.create_image_form.class%
        arguments: [@image.manager, @validator]