register:
    pattern: /registro
    defaults: { _controller: UserBundle:Access:register }
success_register:
    pattern: /registro-completado
    defaults: { _controller: UserBundle:Access:successRegister }