parameters:
    clop.security.authentication.success_handler.class: Ecommerce\FrontendBundle\Component\Security\AuthenticationSuccessHandler

services:
    clop.security.authentication.success_handler:
        class: %clop.security.authentication.success_handler.class%
        public: false
        arguments:  ['@router']