parameters:
    item.item_form_handler.class: Ecommerce\ItemBundle\Form\Handler\ItemFormHandler
    manufacturer.manufacturer_form_handler.class: Ecommerce\ItemBundle\Form\Handler\ManufacturerFormHandler

services:
    item.item_form_handler:
        class: %item.item_form_handler.class%
        arguments: [@doctrine.orm.entity_manager]
    manufacturer.manufacturer_form_handler:
            class: %manufacturer.manufacturer_form_handler.class%
            arguments: [@doctrine.orm.entity_manager]