parameters:
    item.item_form_handler.class: Ecommerce\ItemBundle\Form\Handler\ItemFormHandler

services:
    item.item_form_handler:
        class: %item.item_form_handler.class%
        arguments: [@doctrine.orm.entity_manager]
