parameters:
    subcategory.subcategory_form_handler.class: Ecommerce\CategoryBundle\Form\Handler\SubcategoryFormHandler

services:
    subcategory.subcategory_form_handler:
        class: %subcategory.subcategory_form_handler.class%
        arguments: [@doctrine.orm.entity_manager]
