parameters:
#    payment.example.class: Ecommerce\PaymentBundle\Example

services:
#    payment.example:
#        class: %payment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
