parameters:
    payment.databillingformhandler.class: Ecommerce\PaymentBundle\Form\Handler\DataBillingFormHandler
    payment.databillingmanager.class: Ecommerce\PaymentBundle\Form\Handler\DataBillingManager

services:
    payment.databilling_manager:
        class: %payment.databillingmanager.class%
        arguments: [@doctrine.orm.entity_manager]
    payment.databilling_form_handler:
        class: %payment.databillingformhandler.class%
        arguments: [@payment.databilling_manager, @doctrine.orm.entity_manager]